version: '3.9'

services:
  web:
    # Берем Dockerfile из каталога sinusgraph
    build: ./
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8585:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env